spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/maejjang
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379

#MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*Mapper.xml

#feign
maple:
  api:
    uri:
      id:
      character: /maplestory/v1