spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/maejjang
    username: postgres
    password: 1234

server:
  baseUrl: http://localhost:${server.port}

#logging:
#  level:
#    root: debug
#    'com.maejjang.api': debug
