spring:
  profiles:
    include: secret
    active: loc

#MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*Mapper.xml

#feign
maple:
  api:
    uri:
      id:
      character: https://open.api.nexon.com/maplestory/v1
server:
  port: 8090